// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebDemo.Services;

namespace WebDemo.Migrations
{
    [DbContext(typeof(TodoDBContext))]
    [Migration("20220204011831_Initialv2")]
    partial class Initialv2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebDemo.Entity.Cliente", b =>
                {
                    b.Property<int>("codigoCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CodigoCliente")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("abreviatura")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Abreviatura");

                    b.Property<string>("codigoSap")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CodigoSap");

                    b.Property<string>("estado")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Estado");

                    b.Property<string>("grupoFacturacion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("GrupoFacturacion");

                    b.Property<DateTime>("inactivoDesde")
                        .HasColumnType("datetime2")
                        .HasColumnName("InactivoDesde");

                    b.Property<string>("nombreCompleto")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NombreCompleto");

                    b.Property<string>("nombreCorto")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NombreCorto");

                    b.Property<string>("ruc")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Ruc");

                    b.HasKey("codigoCliente");

                    b.ToTable("Cliente");
                });
#pragma warning restore 612, 618
        }
    }
}
